#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("goheja.Resource", IsApplication=true)]

namespace goheja
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::goheja.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::goheja.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::goheja.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::goheja.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::goheja.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::goheja.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::goheja.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::goheja.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::goheja.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::goheja.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::goheja.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::goheja.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::goheja.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::goheja.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::goheja.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::goheja.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::goheja.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::goheja.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::goheja.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::goheja.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::goheja.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::goheja.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::goheja.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::goheja.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::goheja.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::goheja.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::goheja.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::goheja.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::goheja.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::goheja.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::goheja.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::goheja.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::goheja.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::goheja.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::goheja.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::goheja.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::goheja.Resource.Styleable.ProgressWheel_ahTextSize;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fromLeft = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fromRight = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int header_slide_bottom_in = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int header_slide_bottom_out = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int header_slide_top_in = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int header_slide_top_out = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int slide_bottom_in = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int slide_bottom_out = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int slide_top_in = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int slide_top_out = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int toLeft = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int toRight = 2130968587;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f07000f
			public const int flexChartCerulanPalette = 2131165199;
			
			// aapt resource value: 0x7f070001
			public const int flexChartCocoaPalette = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int flexChartCoralPalette = 2131165186;
			
			// aapt resource value: 0x7f07000b
			public const int flexChartCyborgPalette = 2131165195;
			
			// aapt resource value: 0x7f070003
			public const int flexChartDarkPalette = 2131165187;
			
			// aapt resource value: 0x7f07000e
			public const int flexChartDarklyPalette = 2131165198;
			
			// aapt resource value: 0x7f070000
			public const int flexChartDefaultFlexChartPalette = 2131165184;
			
			// aapt resource value: 0x7f07000d
			public const int flexChartFlatlyPalette = 2131165197;
			
			// aapt resource value: 0x7f070004
			public const int flexChartHighConstrastPalette = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int flexChartLightPalette = 2131165189;
			
			// aapt resource value: 0x7f070010
			public const int flexChartMaterialPalette = 2131165200;
			
			// aapt resource value: 0x7f070006
			public const int flexChartMidnightPalette = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int flexChartMinimalPalette = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int flexChartModernPalette = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int flexChartOrganicPalette = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int flexChartSlatePalette = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int flexChartSuperheroPalette = 2131165196;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01008a
			public const int absoluteMaxValue = 2130772106;
			
			// aapt resource value: 0x7f010089
			public const int absoluteMinValue = 2130772105;
			
			// aapt resource value: 0x7f01009d
			public const int activateOnDefaultValues = 2130772125;
			
			// aapt resource value: 0x7f010093
			public const int activeColor = 2130772115;
			
			// aapt resource value: 0x7f010003
			public const int ahBarColor = 2130771971;
			
			// aapt resource value: 0x7f01000b
			public const int ahBarLength = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int ahBarWidth = 2130771978;
			
			// aapt resource value: 0x7f010008
			public const int ahCircleColor = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int ahDelayMillis = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int ahRadius = 2130771977;
			
			// aapt resource value: 0x7f010004
			public const int ahRimColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int ahRimWidth = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int ahSpinSpeed = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int ahText = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int ahTextColor = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int ahTextSize = 2130771970;
			
			// aapt resource value: 0x7f01008e
			public const int alwaysActive = 2130772110;
			
			// aapt resource value: 0x7f010091
			public const int barHeight = 2130772113;
			
			// aapt resource value: 0x7f010092
			public const int defaultColor = 2130772114;
			
			// aapt resource value: 0x7f010024
			public const int flexChartSeries_chartType = 2130772004;
			
			// aapt resource value: 0x7f010025
			public const int flexChartSeries_visibility = 2130772005;
			
			// aapt resource value: 0x7f010041
			public const int flexChart_animated = 2130772033;
			
			// aapt resource value: 0x7f010017
			public const int flexChart_axisX_axisLineVisible = 2130771991;
			
			// aapt resource value: 0x7f01005c
			public const int flexChart_axisX_format = 2130772060;
			
			// aapt resource value: 0x7f01004c
			public const int flexChart_axisX_labelAngle = 2130772044;
			
			// aapt resource value: 0x7f010049
			public const int flexChart_axisX_labelFontColor = 2130772041;
			
			// aapt resource value: 0x7f01004a
			public const int flexChart_axisX_labelFontSize = 2130772042;
			
			// aapt resource value: 0x7f01004b
			public const int flexChart_axisX_labelFontTypeface = 2130772043;
			
			// aapt resource value: 0x7f010014
			public const int flexChart_axisX_labelFontWeight = 2130771988;
			
			// aapt resource value: 0x7f010016
			public const int flexChart_axisX_labelsVisible = 2130771990;
			
			// aapt resource value: 0x7f010050
			public const int flexChart_axisX_lineColor = 2130772048;
			
			// aapt resource value: 0x7f010051
			public const int flexChart_axisX_lineWidth = 2130772049;
			
			// aapt resource value: 0x7f010062
			public const int flexChart_axisX_logBase = 2130772066;
			
			// aapt resource value: 0x7f010052
			public const int flexChart_axisX_majorGridColor = 2130772050;
			
			// aapt resource value: 0x7f010056
			public const int flexChart_axisX_majorGridFill = 2130772054;
			
			// aapt resource value: 0x7f010019
			public const int flexChart_axisX_majorGridVisible = 2130771993;
			
			// aapt resource value: 0x7f010053
			public const int flexChart_axisX_majorGridWidth = 2130772051;
			
			// aapt resource value: 0x7f010054
			public const int flexChart_axisX_majorTickColor = 2130772052;
			
			// aapt resource value: 0x7f010018
			public const int flexChart_axisX_majorTickOverlap = 2130771992;
			
			// aapt resource value: 0x7f010055
			public const int flexChart_axisX_majorTickWidth = 2130772053;
			
			// aapt resource value: 0x7f01005e
			public const int flexChart_axisX_majorUnit = 2130772062;
			
			// aapt resource value: 0x7f010057
			public const int flexChart_axisX_minorGridColor = 2130772055;
			
			// aapt resource value: 0x7f01005b
			public const int flexChart_axisX_minorGridFill = 2130772059;
			
			// aapt resource value: 0x7f01001b
			public const int flexChart_axisX_minorGridVisible = 2130771995;
			
			// aapt resource value: 0x7f010058
			public const int flexChart_axisX_minorGridWidth = 2130772056;
			
			// aapt resource value: 0x7f010059
			public const int flexChart_axisX_minorTickColor = 2130772057;
			
			// aapt resource value: 0x7f01001a
			public const int flexChart_axisX_minorTickOverlap = 2130771994;
			
			// aapt resource value: 0x7f01005a
			public const int flexChart_axisX_minorTickWidth = 2130772058;
			
			// aapt resource value: 0x7f01005f
			public const int flexChart_axisX_minorUnit = 2130772063;
			
			// aapt resource value: 0x7f010061
			public const int flexChart_axisX_name = 2130772065;
			
			// aapt resource value: 0x7f01005d
			public const int flexChart_axisX_origin = 2130772061;
			
			// aapt resource value: 0x7f010063
			public const int flexChart_axisX_overlappingLabels = 2130772067;
			
			// aapt resource value: 0x7f010060
			public const int flexChart_axisX_title = 2130772064;
			
			// aapt resource value: 0x7f01004d
			public const int flexChart_axisX_titleFontColor = 2130772045;
			
			// aapt resource value: 0x7f01004e
			public const int flexChart_axisX_titleFontSize = 2130772046;
			
			// aapt resource value: 0x7f01004f
			public const int flexChart_axisX_titleFontTypeface = 2130772047;
			
			// aapt resource value: 0x7f010015
			public const int flexChart_axisX_titleFontWeight = 2130771989;
			
			// aapt resource value: 0x7f01001f
			public const int flexChart_axisY_axisLineVisible = 2130771999;
			
			// aapt resource value: 0x7f010064
			public const int flexChart_axisY_format = 2130772068;
			
			// aapt resource value: 0x7f010068
			public const int flexChart_axisY_labelAngle = 2130772072;
			
			// aapt resource value: 0x7f010065
			public const int flexChart_axisY_labelFontColor = 2130772069;
			
			// aapt resource value: 0x7f010066
			public const int flexChart_axisY_labelFontSize = 2130772070;
			
			// aapt resource value: 0x7f010067
			public const int flexChart_axisY_labelFontTypeface = 2130772071;
			
			// aapt resource value: 0x7f01001c
			public const int flexChart_axisY_labelFontWeight = 2130771996;
			
			// aapt resource value: 0x7f01001e
			public const int flexChart_axisY_labelsVisible = 2130771998;
			
			// aapt resource value: 0x7f01006c
			public const int flexChart_axisY_lineColor = 2130772076;
			
			// aapt resource value: 0x7f01006d
			public const int flexChart_axisY_lineWidth = 2130772077;
			
			// aapt resource value: 0x7f01007d
			public const int flexChart_axisY_logBase = 2130772093;
			
			// aapt resource value: 0x7f01006e
			public const int flexChart_axisY_majorGridColor = 2130772078;
			
			// aapt resource value: 0x7f010072
			public const int flexChart_axisY_majorGridFill = 2130772082;
			
			// aapt resource value: 0x7f010020
			public const int flexChart_axisY_majorGridVisible = 2130772000;
			
			// aapt resource value: 0x7f01006f
			public const int flexChart_axisY_majorGridWidth = 2130772079;
			
			// aapt resource value: 0x7f010070
			public const int flexChart_axisY_majorTickColor = 2130772080;
			
			// aapt resource value: 0x7f010021
			public const int flexChart_axisY_majorTickOverlap = 2130772001;
			
			// aapt resource value: 0x7f010071
			public const int flexChart_axisY_majorTickWidth = 2130772081;
			
			// aapt resource value: 0x7f010079
			public const int flexChart_axisY_majorUnit = 2130772089;
			
			// aapt resource value: 0x7f010073
			public const int flexChart_axisY_minorGridColor = 2130772083;
			
			// aapt resource value: 0x7f010077
			public const int flexChart_axisY_minorGridFill = 2130772087;
			
			// aapt resource value: 0x7f010022
			public const int flexChart_axisY_minorGridVisible = 2130772002;
			
			// aapt resource value: 0x7f010074
			public const int flexChart_axisY_minorGridWidth = 2130772084;
			
			// aapt resource value: 0x7f010075
			public const int flexChart_axisY_minorTickColor = 2130772085;
			
			// aapt resource value: 0x7f010023
			public const int flexChart_axisY_minorTickOverlap = 2130772003;
			
			// aapt resource value: 0x7f010076
			public const int flexChart_axisY_minorTickWidth = 2130772086;
			
			// aapt resource value: 0x7f01007a
			public const int flexChart_axisY_minorUnit = 2130772090;
			
			// aapt resource value: 0x7f01007c
			public const int flexChart_axisY_name = 2130772092;
			
			// aapt resource value: 0x7f010078
			public const int flexChart_axisY_origin = 2130772088;
			
			// aapt resource value: 0x7f01007e
			public const int flexChart_axisY_overlappingLabels = 2130772094;
			
			// aapt resource value: 0x7f01007b
			public const int flexChart_axisY_title = 2130772091;
			
			// aapt resource value: 0x7f010069
			public const int flexChart_axisY_titleFontColor = 2130772073;
			
			// aapt resource value: 0x7f01006a
			public const int flexChart_axisY_titleFontSize = 2130772074;
			
			// aapt resource value: 0x7f01006b
			public const int flexChart_axisY_titleFontTypeface = 2130772075;
			
			// aapt resource value: 0x7f01001d
			public const int flexChart_axisY_titleFontWeight = 2130771997;
			
			// aapt resource value: 0x7f01002f
			public const int flexChart_backgroundColor = 2130772015;
			
			// aapt resource value: 0x7f010040
			public const int flexChart_binding = 2130772032;
			
			// aapt resource value: 0x7f010030
			public const int flexChart_borderColor = 2130772016;
			
			// aapt resource value: 0x7f010031
			public const int flexChart_borderWidth = 2130772017;
			
			// aapt resource value: 0x7f01003e
			public const int flexChart_chartOptions_bubbleMaxSize = 2130772030;
			
			// aapt resource value: 0x7f01003d
			public const int flexChart_chartOptions_bubbleMinSize = 2130772029;
			
			// aapt resource value: 0x7f01003f
			public const int flexChart_chartOptions_groupWidth = 2130772031;
			
			// aapt resource value: 0x7f010012
			public const int flexChart_chartType = 2130771986;
			
			// aapt resource value: 0x7f010082
			public const int flexChart_datalabel_FontColor = 2130772098;
			
			// aapt resource value: 0x7f010084
			public const int flexChart_datalabel_FontSize = 2130772100;
			
			// aapt resource value: 0x7f010085
			public const int flexChart_datalabel_FontTypeface = 2130772101;
			
			// aapt resource value: 0x7f010011
			public const int flexChart_datalabel_FontWeight = 2130771985;
			
			// aapt resource value: 0x7f010080
			public const int flexChart_datalabel_backgroundColor = 2130772096;
			
			// aapt resource value: 0x7f010081
			public const int flexChart_datalabel_borderColor = 2130772097;
			
			// aapt resource value: 0x7f010083
			public const int flexChart_datalabel_borderWidth = 2130772099;
			
			// aapt resource value: 0x7f01007f
			public const int flexChart_datalabel_position = 2130772095;
			
			// aapt resource value: 0x7f01002b
			public const int flexChart_footer = 2130772011;
			
			// aapt resource value: 0x7f01002e
			public const int flexChart_footerFontColor = 2130772014;
			
			// aapt resource value: 0x7f01000f
			public const int flexChart_footerFontGravity = 2130771983;
			
			// aapt resource value: 0x7f01002c
			public const int flexChart_footerFontSize = 2130772012;
			
			// aapt resource value: 0x7f01002d
			public const int flexChart_footerFontTypeface = 2130772013;
			
			// aapt resource value: 0x7f01000e
			public const int flexChart_footerFontWeight = 2130771982;
			
			// aapt resource value: 0x7f010027
			public const int flexChart_header = 2130772007;
			
			// aapt resource value: 0x7f01002a
			public const int flexChart_headerFontColor = 2130772010;
			
			// aapt resource value: 0x7f01000d
			public const int flexChart_headerFontGravity = 2130771981;
			
			// aapt resource value: 0x7f010028
			public const int flexChart_headerFontSize = 2130772008;
			
			// aapt resource value: 0x7f010029
			public const int flexChart_headerFontTypeface = 2130772009;
			
			// aapt resource value: 0x7f01000c
			public const int flexChart_headerFontWeight = 2130771980;
			
			// aapt resource value: 0x7f010038
			public const int flexChart_legend_FontColor = 2130772024;
			
			// aapt resource value: 0x7f010039
			public const int flexChart_legend_FontSize = 2130772025;
			
			// aapt resource value: 0x7f01003a
			public const int flexChart_legend_FontTypeface = 2130772026;
			
			// aapt resource value: 0x7f010010
			public const int flexChart_legend_FontWeight = 2130771984;
			
			// aapt resource value: 0x7f010035
			public const int flexChart_legend_backgroundColor = 2130772021;
			
			// aapt resource value: 0x7f010036
			public const int flexChart_legend_borderColor = 2130772022;
			
			// aapt resource value: 0x7f010037
			public const int flexChart_legend_borderWidth = 2130772023;
			
			// aapt resource value: 0x7f01003b
			public const int flexChart_legend_orientation = 2130772027;
			
			// aapt resource value: 0x7f01003c
			public const int flexChart_legend_position = 2130772028;
			
			// aapt resource value: 0x7f010045
			public const int flexChart_loadAnimation_duration = 2130772037;
			
			// aapt resource value: 0x7f010044
			public const int flexChart_loadAnimation_loadAnimationMode = 2130772036;
			
			// aapt resource value: 0x7f010046
			public const int flexChart_loadAnimation_startDelay = 2130772038;
			
			// aapt resource value: 0x7f010026
			public const int flexChart_palette = 2130772006;
			
			// aapt resource value: 0x7f010032
			public const int flexChart_plotAreabackgroundColor = 2130772018;
			
			// aapt resource value: 0x7f010033
			public const int flexChart_selectedBorderColor = 2130772019;
			
			// aapt resource value: 0x7f010034
			public const int flexChart_selectedBorderWidth = 2130772020;
			
			// aapt resource value: 0x7f010013
			public const int flexChart_stackingType = 2130771987;
			
			// aapt resource value: 0x7f010043
			public const int flexChart_toggleLegend = 2130772035;
			
			// aapt resource value: 0x7f010047
			public const int flexChart_updateAnimation_duration = 2130772039;
			
			// aapt resource value: 0x7f010048
			public const int flexChart_updateAnimation_startDelay = 2130772040;
			
			// aapt resource value: 0x7f010042
			public const int flexChart_zoomMode = 2130772034;
			
			// aapt resource value: 0x7f010090
			public const int internalPadding = 2130772112;
			
			// aapt resource value: 0x7f01008c
			public const int maxThumbHidden = 2130772108;
			
			// aapt resource value: 0x7f010086
			public const int minTextSize = 2130772102;
			
			// aapt resource value: 0x7f01008b
			public const int minThumbHidden = 2130772107;
			
			// aapt resource value: 0x7f010087
			public const int precision = 2130772103;
			
			// aapt resource value: 0x7f01008d
			public const int showRangeLabels = 2130772109;
			
			// aapt resource value: 0x7f010088
			public const int sizeToFit = 2130772104;
			
			// aapt resource value: 0x7f01009e
			public const int stepValue = 2130772126;
			
			// aapt resource value: 0x7f01009f
			public const int stepValueContinuously = 2130772127;
			
			// aapt resource value: 0x7f010094
			public const int textAboveThumbsColor = 2130772116;
			
			// aapt resource value: 0x7f0100a0
			public const int textSize = 2130772128;
			
			// aapt resource value: 0x7f010097
			public const int thumbDisabled = 2130772119;
			
			// aapt resource value: 0x7f010095
			public const int thumbNormal = 2130772117;
			
			// aapt resource value: 0x7f010096
			public const int thumbPressed = 2130772118;
			
			// aapt resource value: 0x7f010098
			public const int thumbShadow = 2130772120;
			
			// aapt resource value: 0x7f01009c
			public const int thumbShadowBlur = 2130772124;
			
			// aapt resource value: 0x7f010099
			public const int thumbShadowColor = 2130772121;
			
			// aapt resource value: 0x7f01009a
			public const int thumbShadowXOffset = 2130772122;
			
			// aapt resource value: 0x7f01009b
			public const int thumbShadowYOffset = 2130772123;
			
			// aapt resource value: 0x7f01008f
			public const int valuesAboveThumbs = 2130772111;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int active_tab = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrow_icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bg_new = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bg_performance = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bikeRound_new = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int border = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int border_bottom = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int border_vertical = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int button = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int cell_icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int dct = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int dist_new = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int down_black = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int down_gray = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int down_white = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int edit_icon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int email_icon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int go_button = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int header = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int heart_new = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int home_icon = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int horizontal_line = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_errorstatus = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_successstatus = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int icon = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int icon_ = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int icon_01 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int icon_02 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int icon_03 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int icon_03_inactive = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int icon_04 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int icon_04_inactive = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int icon_05 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int icon_05_inactive = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int icon_06 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int icon_06_inactive = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int icon_07 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int icon_07_inactive = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int icon_back = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int icon_bike = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int icon_calendar = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int icon_changepw = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int icon_check = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int icon_check2 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int icon_clock = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int icon_cross = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int icon_delete = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int icon_down = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int icon_email = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int icon_error = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int icon_exit = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int icon_group_report = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int icon_home = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int icon_left = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int icon_lock = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int icon_logo = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int icon_logo_new = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int icon_map_pin = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int icon_notification = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int icon_other = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int icon_pencil = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int icon_phone = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int icon_right = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int icon_run = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int icon_swim = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int icon_sync = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int icon_triathlon = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int icon_user = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int icon_user_white = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int icon_whistle = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int icon_workout_report = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int img_bg = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int left_black = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int left_gray = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int left_white = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int line_new = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int mont_new = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int ninja = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int no_photo_round = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int pin_camera = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int pin_check_mark = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int pin_east = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int pin_finish = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int pin_me = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int pin_north = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int pin_pfinish = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int pin_pstart = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int pin_south = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int pin_start = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int pin_T1 = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int pin_T2 = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int pin_west = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int pop_up_bg = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int resume_active = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int resume_inactive = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int right_black = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int right_gray = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int right_white = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int roundedbg = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int roundedbgdark = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int runRound_new = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int speed_new = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int splash = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int splash_new = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int stop_active = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int switch_off = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int timer_new = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int up_black = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int up_gray = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int up_white = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int watt_new = 2130837614;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08009c
			public const int AAAA = 2131230876;
			
			// aapt resource value: 0x7f08001e
			public const int ALL = 2131230750;
			
			// aapt resource value: 0x7f080007
			public const int AREA = 2131230727;
			
			// aapt resource value: 0x7f080021
			public const int AUTO = 2131230753;
			
			// aapt resource value: 0x7f080033
			public const int ActionAddComment = 2131230771;
			
			// aapt resource value: 0x7f08004b
			public const int ActionAdjustTrainning = 2131230795;
			
			// aapt resource value: 0x7f08006b
			public const int ActionBack = 2131230827;
			
			// aapt resource value: 0x7f08002d
			public const int ActionBar = 2131230765;
			
			// aapt resource value: 0x7f08017f
			public const int ActionBarMain = 2131231103;
			
			// aapt resource value: 0x7f08014b
			public const int ActionChangePassword = 2131231051;
			
			// aapt resource value: 0x7f080156
			public const int ActionClose = 2131231062;
			
			// aapt resource value: 0x7f080174
			public const int ActionCycling = 2131231092;
			
			// aapt resource value: 0x7f080043
			public const int ActionDistanceChanged = 2131230787;
			
			// aapt resource value: 0x7f080149
			public const int ActionEditProfile = 2131231049;
			
			// aapt resource value: 0x7f08014f
			public const int ActionEventDetail = 2131231055;
			
			// aapt resource value: 0x7f080160
			public const int ActionForgotPassword = 2131231072;
			
			// aapt resource value: 0x7f080107
			public const int ActionLocation = 2131230983;
			
			// aapt resource value: 0x7f080161
			public const int ActionLogin = 2131231073;
			
			// aapt resource value: 0x7f080159
			public const int ActionNavigate = 2131231065;
			
			// aapt resource value: 0x7f08017c
			public const int ActionOther = 2131231100;
			
			// aapt resource value: 0x7f0800df
			public const int ActionReload = 2131230943;
			
			// aapt resource value: 0x7f080076
			public const int ActionResetPassword = 2131230838;
			
			// aapt resource value: 0x7f080176
			public const int ActionRunning = 2131231094;
			
			// aapt resource value: 0x7f08014d
			public const int ActionSignIn = 2131231053;
			
			// aapt resource value: 0x7f08014c
			public const int ActionSignOut = 2131231052;
			
			// aapt resource value: 0x7f08014e
			public const int ActionSignUp = 2131231054;
			
			// aapt resource value: 0x7f080178
			public const int ActionSwimming = 2131231096;
			
			// aapt resource value: 0x7f080034
			public const int ActionSwitchType = 2131230772;
			
			// aapt resource value: 0x7f08014a
			public const int ActionSyncDevice = 2131231050;
			
			// aapt resource value: 0x7f080047
			public const int ActionTSSChanged = 2131230791;
			
			// aapt resource value: 0x7f080172
			public const int ActionTerms = 2131231090;
			
			// aapt resource value: 0x7f08003f
			public const int ActionTimeChanged = 2131230783;
			
			// aapt resource value: 0x7f0800e0
			public const int ActionToday = 2131230944;
			
			// aapt resource value: 0x7f080114
			public const int ActionToggleATL = 2131230996;
			
			// aapt resource value: 0x7f080117
			public const int ActionToggleCTL = 2131230999;
			
			// aapt resource value: 0x7f08011d
			public const int ActionToggleDailyIf = 2131231005;
			
			// aapt resource value: 0x7f08011a
			public const int ActionToggleDailyLoad = 2131231002;
			
			// aapt resource value: 0x7f080110
			public const int ActionToggleTSB = 2131230992;
			
			// aapt resource value: 0x7f08017a
			public const int ActionTriathlon = 2131231098;
			
			// aapt resource value: 0x7f08013c
			public const int ActionType0 = 2131231036;
			
			// aapt resource value: 0x7f08013d
			public const int ActionType1 = 2131231037;
			
			// aapt resource value: 0x7f08013e
			public const int ActionType2 = 2131231038;
			
			// aapt resource value: 0x7f08013f
			public const int ActionType3 = 2131231039;
			
			// aapt resource value: 0x7f080140
			public const int ActionType4 = 2131231040;
			
			// aapt resource value: 0x7f080141
			public const int ActionType5 = 2131231041;
			
			// aapt resource value: 0x7f080142
			public const int ActionType6 = 2131231042;
			
			// aapt resource value: 0x7f08010e
			public const int ActionViewCalendar = 2131230990;
			
			// aapt resource value: 0x7f08002a
			public const int Auto = 2131230762;
			
			// aapt resource value: 0x7f080008
			public const int BAR = 2131230728;
			
			// aapt resource value: 0x7f080000
			public const int BOLD = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int BOLD_ITALIC = 2131230721;
			
			// aapt resource value: 0x7f080022
			public const int BOTTOM = 2131230754;
			
			// aapt resource value: 0x7f080009
			public const int BUBBLE = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int CANDLE = 2131230730;
			
			// aapt resource value: 0x7f08002c
			public const int CENTER = 2131230764;
			
			// aapt resource value: 0x7f080004
			public const int CENTER_HORIZONTAL = 2131230724;
			
			// aapt resource value: 0x7f08000b
			public const int COLUMN = 2131230731;
			
			// aapt resource value: 0x7f080024
			public const int DISABLED = 2131230756;
			
			// aapt resource value: 0x7f080016
			public const int FALSE = 2131230742;
			
			// aapt resource value: 0x7f08001a
			public const int HIDDEN = 2131230746;
			
			// aapt resource value: 0x7f08000c
			public const int HLOC = 2131230732;
			
			// aapt resource value: 0x7f08001f
			public const int HORIZONTAL = 2131230751;
			
			// aapt resource value: 0x7f080018
			public const int INSIDE = 2131230744;
			
			// aapt resource value: 0x7f080002
			public const int ITALIC = 2131230722;
			
			// aapt resource value: 0x7f08006e
			public const int ImageView1 = 2131230830;
			
			// aapt resource value: 0x7f080005
			public const int LEFT = 2131230725;
			
			// aapt resource value: 0x7f08001b
			public const int LEGEND = 2131230747;
			
			// aapt resource value: 0x7f08000d
			public const int LINE = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int LINESYMBOLS = 2131230734;
			
			// aapt resource value: 0x7f080050
			public const int LinearLayout1 = 2131230800;
			
			// aapt resource value: 0x7f080059
			public const int LinearLayout2 = 2131230809;
			
			// aapt resource value: 0x7f08005e
			public const int LinearLayout3 = 2131230814;
			
			// aapt resource value: 0x7f080013
			public const int NONE = 2131230739;
			
			// aapt resource value: 0x7f080003
			public const int NORMAL = 2131230723;
			
			// aapt resource value: 0x7f080019
			public const int OUTSIDE = 2131230745;
			
			// aapt resource value: 0x7f08001c
			public const int PLOT = 2131230748;
			
			// aapt resource value: 0x7f080028
			public const int POINT = 2131230760;
			
			// aapt resource value: 0x7f080006
			public const int RIGHT = 2131230726;
			
			// aapt resource value: 0x7f08000f
			public const int SCATTER = 2131230735;
			
			// aapt resource value: 0x7f080029
			public const int SERIES = 2131230761;
			
			// aapt resource value: 0x7f080010
			public const int SPLINE = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int SPLINEAREA = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int SPLINESYMBOLS = 2131230738;
			
			// aapt resource value: 0x7f080014
			public const int STACKED = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int STACKED100pc = 2131230741;
			
			// aapt resource value: 0x7f08002b
			public const int Show = 2131230763;
			
			// aapt resource value: 0x7f080023
			public const int TOP = 2131230755;
			
			// aapt resource value: 0x7f080017
			public const int TRUE = 2131230743;
			
			// aapt resource value: 0x7f080181
			public const int Tab1Icon = 2131231105;
			
			// aapt resource value: 0x7f080183
			public const int Tab2Icon = 2131231107;
			
			// aapt resource value: 0x7f080186
			public const int Tab3Icon = 2131231110;
			
			// aapt resource value: 0x7f08004c
			public const int TitleBarText = 2131230796;
			
			// aapt resource value: 0x7f080020
			public const int VERTICAL = 2131230752;
			
			// aapt resource value: 0x7f08001d
			public const int VISIBLE = 2131230749;
			
			// aapt resource value: 0x7f080025
			public const int X = 2131230757;
			
			// aapt resource value: 0x7f080026
			public const int XY = 2131230758;
			
			// aapt resource value: 0x7f080027
			public const int Y = 2131230759;
			
			// aapt resource value: 0x7f080069
			public const int annotationTooltipContent = 2131230825;
			
			// aapt resource value: 0x7f08009a
			public const int bestresults = 2131230874;
			
			// aapt resource value: 0x7f080120
			public const int bgSymbolCycling = 2131231008;
			
			// aapt resource value: 0x7f080129
			public const int bgSymbolRunning = 2131231017;
			
			// aapt resource value: 0x7f080131
			public const int bgSymbolSwimming = 2131231025;
			
			// aapt resource value: 0x7f080036
			public const int bgType = 2131230774;
			
			// aapt resource value: 0x7f080068
			public const int btnBack = 2131230824;
			
			// aapt resource value: 0x7f08003a
			public const int btnCycle = 2131230778;
			
			// aapt resource value: 0x7f080067
			public const int btnLD = 2131230823;
			
			// aapt resource value: 0x7f080108
			public const int btnRun = 2131230984;
			
			// aapt resource value: 0x7f080064
			public const int btnStartPause = 2131230820;
			
			// aapt resource value: 0x7f080065
			public const int btnStop = 2131230821;
			
			// aapt resource value: 0x7f080132
			public const int btnSwim = 2131231026;
			
			// aapt resource value: 0x7f08005d
			public const int btnTotalTime = 2131230813;
			
			// aapt resource value: 0x7f0800de
			public const int btnUpdate = 2131230942;
			
			// aapt resource value: 0x7f0800e2
			public const int calendar = 2131230946;
			
			// aapt resource value: 0x7f080077
			public const int calendar_item_tv_day = 2131230839;
			
			// aapt resource value: 0x7f08015a
			public const int calendaritem = 2131231066;
			
			// aapt resource value: 0x7f08010f
			public const int chartContent = 2131230991;
			
			// aapt resource value: 0x7f08003b
			public const int checkAttended = 2131230779;
			
			// aapt resource value: 0x7f080171
			public const int checkTerms = 2131231089;
			
			// aapt resource value: 0x7f080106
			public const int collapsCycle = 2131230982;
			
			// aapt resource value: 0x7f080128
			public const int collapsRun = 2131231016;
			
			// aapt resource value: 0x7f080130
			public const int collapsSwim = 2131231024;
			
			// aapt resource value: 0x7f08009b
			public const int collapseBestResults = 2131230875;
			
			// aapt resource value: 0x7f080093
			public const int collapseGoals = 2131230867;
			
			// aapt resource value: 0x7f08008b
			public const int collapsePhysical = 2131230859;
			
			// aapt resource value: 0x7f0800a7
			public const int collapseSelfRanking = 2131230887;
			
			// aapt resource value: 0x7f080063
			public const int content = 2131230819;
			
			// aapt resource value: 0x7f08010b
			public const int contentComment = 2131230987;
			
			// aapt resource value: 0x7f08007c
			public const int contentView = 2131230844;
			
			// aapt resource value: 0x7f08004d
			public const int drawerHandleLayout = 2131230797;
			
			// aapt resource value: 0x7f080066
			public const int dummyType = 2131230822;
			
			// aapt resource value: 0x7f08009d
			public const int edtBestResults = 2131230877;
			
			// aapt resource value: 0x7f0800d0
			public const int edtBike = 2131230928;
			
			// aapt resource value: 0x7f080095
			public const int edtGoals = 2131230869;
			
			// aapt resource value: 0x7f08008c
			public const int edtPhysical = 2131230860;
			
			// aapt resource value: 0x7f0800bd
			public const int edtRun = 2131230909;
			
			// aapt resource value: 0x7f0800a8
			public const int edtSeflRanking = 2131230888;
			
			// aapt resource value: 0x7f0800b0
			public const int edtSwim = 2131230896;
			
			// aapt resource value: 0x7f080146
			public const int errorEmail = 2131231046;
			
			// aapt resource value: 0x7f080164
			public const int errorFirstname = 2131231076;
			
			// aapt resource value: 0x7f080167
			public const int errorLastname = 2131231079;
			
			// aapt resource value: 0x7f080071
			public const int errorPassword = 2131230833;
			
			// aapt resource value: 0x7f080075
			public const int errorPwConfirm = 2131230837;
			
			// aapt resource value: 0x7f08016b
			public const int errorUsername = 2131231083;
			
			// aapt resource value: 0x7f0800e4
			public const int eventsList = 2131230948;
			
			// aapt resource value: 0x7f080092
			public const int goals = 2131230866;
			
			// aapt resource value: 0x7f080055
			public const int imageView1 = 2131230805;
			
			// aapt resource value: 0x7f080056
			public const int imageView100 = 2131230806;
			
			// aapt resource value: 0x7f08005c
			public const int imageView103 = 2131230812;
			
			// aapt resource value: 0x7f080072
			public const int imageView2 = 2131230834;
			
			// aapt resource value: 0x7f080147
			public const int imgProfile = 2131231047;
			
			// aapt resource value: 0x7f0800af
			public const int imgSwim = 2131230895;
			
			// aapt resource value: 0x7f080037
			public const int imgType = 2131230775;
			
			// aapt resource value: 0x7f080170
			public const int invalidAge = 2131231088;
			
			// aapt resource value: 0x7f080145
			public const int invalidEmail = 2131231045;
			
			// aapt resource value: 0x7f080163
			public const int invalidFirstname = 2131231075;
			
			// aapt resource value: 0x7f080166
			public const int invalidLastname = 2131231078;
			
			// aapt resource value: 0x7f080070
			public const int invalidPassword = 2131230832;
			
			// aapt resource value: 0x7f080074
			public const int invalidPwConfirm = 2131230836;
			
			// aapt resource value: 0x7f080173
			public const int invalidTerms = 2131231091;
			
			// aapt resource value: 0x7f08016a
			public const int invalidUsername = 2131231082;
			
			// aapt resource value: 0x7f0800ea
			public const int lblATL = 2131230954;
			
			// aapt resource value: 0x7f080082
			public const int lblAddress = 2131230850;
			
			// aapt resource value: 0x7f080084
			public const int lblAge = 2131230852;
			
			// aapt resource value: 0x7f080150
			public const int lblAuthorName = 2131231056;
			
			// aapt resource value: 0x7f080102
			public const int lblAvgHR = 2131230978;
			
			// aapt resource value: 0x7f080104
			public const int lblAvgPower = 2131230980;
			
			// aapt resource value: 0x7f0800fe
			public const int lblAvgSpeed = 2131230974;
			
			// aapt resource value: 0x7f080083
			public const int lblBib = 2131230851;
			
			// aapt resource value: 0x7f080086
			public const int lblBirth = 2131230854;
			
			// aapt resource value: 0x7f0800e8
			public const int lblCTL = 2131230952;
			
			// aapt resource value: 0x7f080152
			public const int lblComment = 2131231058;
			
			// aapt resource value: 0x7f080151
			public const int lblCommentDate = 2131231057;
			
			// aapt resource value: 0x7f08010a
			public const int lblCommentTitle = 2131230986;
			
			// aapt resource value: 0x7f080081
			public const int lblCountry = 2131230849;
			
			// aapt resource value: 0x7f080124
			public const int lblCycleDistance = 2131231012;
			
			// aapt resource value: 0x7f080123
			public const int lblCycleDistanceTitle = 2131231011;
			
			// aapt resource value: 0x7f080122
			public const int lblCycleDuration = 2131231010;
			
			// aapt resource value: 0x7f080121
			public const int lblCycleDurationTitle = 2131231009;
			
			// aapt resource value: 0x7f080127
			public const int lblCycleStress = 2131231015;
			
			// aapt resource value: 0x7f080125
			public const int lblCycleStressTitle = 2131231013;
			
			// aapt resource value: 0x7f0800f3
			public const int lblData = 2131230963;
			
			// aapt resource value: 0x7f080157
			public const int lblDescription = 2131231063;
			
			// aapt resource value: 0x7f080042
			public const int lblDistance = 2131230786;
			
			// aapt resource value: 0x7f080100
			public const int lblElapsedTime = 2131230976;
			
			// aapt resource value: 0x7f080087
			public const int lblEmail = 2131230855;
			
			// aapt resource value: 0x7f08007f
			public const int lblFirstname = 2131230847;
			
			// aapt resource value: 0x7f080085
			public const int lblGender = 2131230853;
			
			// aapt resource value: 0x7f080158
			public const int lblInterval = 2131231064;
			
			// aapt resource value: 0x7f080080
			public const int lblLastname = 2131230848;
			
			// aapt resource value: 0x7f080105
			public const int lblLeveledPower = 2131230981;
			
			// aapt resource value: 0x7f0800eb
			public const int lblLoad = 2131230955;
			
			// aapt resource value: 0x7f080155
			public const int lblName = 2131231061;
			
			// aapt resource value: 0x7f0800e6
			public const int lblNoEvent = 2131230950;
			
			// aapt resource value: 0x7f0800f7
			public const int lblPDistance = 2131230967;
			
			// aapt resource value: 0x7f0800f8
			public const int lblPDuration = 2131230968;
			
			// aapt resource value: 0x7f0800fa
			public const int lblPHB = 2131230970;
			
			// aapt resource value: 0x7f0800f9
			public const int lblPLoad = 2131230969;
			
			// aapt resource value: 0x7f080088
			public const int lblPhone = 2131230856;
			
			// aapt resource value: 0x7f08012d
			public const int lblRunDistance = 2131231021;
			
			// aapt resource value: 0x7f08012c
			public const int lblRunDistanceTitle = 2131231020;
			
			// aapt resource value: 0x7f08012b
			public const int lblRunDuration = 2131231019;
			
			// aapt resource value: 0x7f08012a
			public const int lblRunDurationTitle = 2131231018;
			
			// aapt resource value: 0x7f08012f
			public const int lblRunStress = 2131231023;
			
			// aapt resource value: 0x7f08012e
			public const int lblRunStressTitle = 2131231022;
			
			// aapt resource value: 0x7f0800f0
			public const int lblStartDate = 2131230960;
			
			// aapt resource value: 0x7f080137
			public const int lblSwimDistance = 2131231031;
			
			// aapt resource value: 0x7f080136
			public const int lblSwimDistanceTitle = 2131231030;
			
			// aapt resource value: 0x7f080135
			public const int lblSwimDuration = 2131231029;
			
			// aapt resource value: 0x7f080134
			public const int lblSwimDurationTitle = 2131231028;
			
			// aapt resource value: 0x7f080139
			public const int lblSwimStress = 2131231033;
			
			// aapt resource value: 0x7f080138
			public const int lblSwimStressTitle = 2131231032;
			
			// aapt resource value: 0x7f0800e7
			public const int lblTSB = 2131230951;
			
			// aapt resource value: 0x7f080046
			public const int lblTSS = 2131230790;
			
			// aapt resource value: 0x7f08003e
			public const int lblTime = 2131230782;
			
			// aapt resource value: 0x7f0800ee
			public const int lblTitle = 2131230958;
			
			// aapt resource value: 0x7f080101
			public const int lblTotalAcent = 2131230977;
			
			// aapt resource value: 0x7f080103
			public const int lblTotalCalories = 2131230979;
			
			// aapt resource value: 0x7f0800ff
			public const int lblTotalDistance = 2131230975;
			
			// aapt resource value: 0x7f080148
			public const int lblUsername = 2131231048;
			
			// aapt resource value: 0x7f08002e
			public const int linearLayout1 = 2131230766;
			
			// aapt resource value: 0x7f08003c
			public const int linearLayout10 = 2131230780;
			
			// aapt resource value: 0x7f080052
			public const int linearLayout100 = 2131230802;
			
			// aapt resource value: 0x7f080057
			public const int linearLayout101 = 2131230807;
			
			// aapt resource value: 0x7f08005a
			public const int linearLayout102 = 2131230810;
			
			// aapt resource value: 0x7f08005f
			public const int linearLayout104 = 2131230815;
			
			// aapt resource value: 0x7f080061
			public const int linearLayout105 = 2131230817;
			
			// aapt resource value: 0x7f080048
			public const int linearLayout11 = 2131230792;
			
			// aapt resource value: 0x7f08003d
			public const int linearLayout12 = 2131230781;
			
			// aapt resource value: 0x7f080040
			public const int linearLayout13 = 2131230784;
			
			// aapt resource value: 0x7f08006a
			public const int linearLayout14 = 2131230826;
			
			// aapt resource value: 0x7f080044
			public const int linearLayout15 = 2131230788;
			
			// aapt resource value: 0x7f08006d
			public const int linearLayout16 = 2131230829;
			
			// aapt resource value: 0x7f08004a
			public const int linearLayout17 = 2131230794;
			
			// aapt resource value: 0x7f0800f6
			public const int linearLayout18 = 2131230966;
			
			// aapt resource value: 0x7f0800f2
			public const int linearLayout19 = 2131230962;
			
			// aapt resource value: 0x7f08007a
			public const int linearLayout2 = 2131230842;
			
			// aapt resource value: 0x7f080126
			public const int linearLayout20 = 2131231014;
			
			// aapt resource value: 0x7f08013a
			public const int linearLayout21 = 2131231034;
			
			// aapt resource value: 0x7f0800ec
			public const int linearLayout22 = 2131230956;
			
			// aapt resource value: 0x7f0800ed
			public const int linearLayout23 = 2131230957;
			
			// aapt resource value: 0x7f0800ef
			public const int linearLayout24 = 2131230959;
			
			// aapt resource value: 0x7f0800fc
			public const int linearLayout25 = 2131230972;
			
			// aapt resource value: 0x7f0800f4
			public const int linearLayout26 = 2131230964;
			
			// aapt resource value: 0x7f0800fd
			public const int linearLayout27 = 2131230973;
			
			// aapt resource value: 0x7f080111
			public const int linearLayout28 = 2131230993;
			
			// aapt resource value: 0x7f08010c
			public const int linearLayout29 = 2131230988;
			
			// aapt resource value: 0x7f0800dd
			public const int linearLayout3 = 2131230941;
			
			// aapt resource value: 0x7f08010d
			public const int linearLayout30 = 2131230989;
			
			// aapt resource value: 0x7f08004f
			public const int linearLayout4 = 2131230799;
			
			// aapt resource value: 0x7f0800aa
			public const int linearLayout5 = 2131230890;
			
			// aapt resource value: 0x7f0800ae
			public const int linearLayout6 = 2131230894;
			
			// aapt resource value: 0x7f080032
			public const int linearLayout7 = 2131230770;
			
			// aapt resource value: 0x7f080030
			public const int linearLayout8 = 2131230768;
			
			// aapt resource value: 0x7f080035
			public const int linearLayout9 = 2131230773;
			
			// aapt resource value: 0x7f08015d
			public const int loadingImage = 2131231069;
			
			// aapt resource value: 0x7f08015b
			public const int loadingProgressBar = 2131231067;
			
			// aapt resource value: 0x7f08015e
			public const int loadingProgressWheel = 2131231070;
			
			// aapt resource value: 0x7f08004e
			public const int map = 2131230798;
			
			// aapt resource value: 0x7f08015f
			public const int map_place_box = 2131231071;
			
			// aapt resource value: 0x7f0800e5
			public const int noEventsContent = 2131230949;
			
			// aapt resource value: 0x7f08016d
			public const int note = 2131231085;
			
			// aapt resource value: 0x7f08017e
			public const int pager = 2131231102;
			
			// aapt resource value: 0x7f08008a
			public const int physical = 2131230858;
			
			// aapt resource value: 0x7f08007d
			public const int profile = 2131230845;
			
			// aapt resource value: 0x7f08007e
			public const int relativeLayout1 = 2131230846;
			
			// aapt resource value: 0x7f080089
			public const int relativeLayout2 = 2131230857;
			
			// aapt resource value: 0x7f080168
			public const int relativeLayout4 = 2131231080;
			
			// aapt resource value: 0x7f080143
			public const int relativeLayout5 = 2131231043;
			
			// aapt resource value: 0x7f08006c
			public const int relativeLayout6 = 2131230828;
			
			// aapt resource value: 0x7f08016e
			public const int relativeLayout7 = 2131231086;
			
			// aapt resource value: 0x7f08007b
			public const int scrollView = 2131230843;
			
			// aapt resource value: 0x7f0800e3
			public const int scrollView1 = 2131230947;
			
			// aapt resource value: 0x7f0800a6
			public const int selfrankings = 2131230886;
			
			// aapt resource value: 0x7f080051
			public const int speedFL = 2131230801;
			
			// aapt resource value: 0x7f080054
			public const int speedTv = 2131230804;
			
			// aapt resource value: 0x7f080175
			public const int stateCycling = 2131231093;
			
			// aapt resource value: 0x7f08017d
			public const int stateOther = 2131231101;
			
			// aapt resource value: 0x7f080177
			public const int stateRunning = 2131231095;
			
			// aapt resource value: 0x7f080179
			public const int stateSwimming = 2131231097;
			
			// aapt resource value: 0x7f08017b
			public const int stateTriathlon = 2131231099;
			
			// aapt resource value: 0x7f080038
			public const int strType = 2131230776;
			
			// aapt resource value: 0x7f080115
			public const int symATL = 2131230997;
			
			// aapt resource value: 0x7f080118
			public const int symCTL = 2131231000;
			
			// aapt resource value: 0x7f08011e
			public const int symDailyIF = 2131231006;
			
			// aapt resource value: 0x7f08011b
			public const int symDailyTSS = 2131231003;
			
			// aapt resource value: 0x7f080112
			public const int symTSB = 2131230994;
			
			// aapt resource value: 0x7f080182
			public const int tabAnalytics = 2131231106;
			
			// aapt resource value: 0x7f080180
			public const int tabCalendar = 2131231104;
			
			// aapt resource value: 0x7f080185
			public const int tabProfile = 2131231109;
			
			// aapt resource value: 0x7f08002f
			public const int textView1 = 2131230767;
			
			// aapt resource value: 0x7f080039
			public const int textView2 = 2131230777;
			
			// aapt resource value: 0x7f080041
			public const int textView3 = 2131230785;
			
			// aapt resource value: 0x7f080045
			public const int textView4 = 2131230789;
			
			// aapt resource value: 0x7f080049
			public const int textView5 = 2131230793;
			
			// aapt resource value: 0x7f0800e9
			public const int textView6 = 2131230953;
			
			// aapt resource value: 0x7f08015c
			public const int textViewStatus = 2131231068;
			
			// aapt resource value: 0x7f080094
			public const int textview111 = 2131230868;
			
			// aapt resource value: 0x7f080079
			public const int tooltipContent = 2131230841;
			
			// aapt resource value: 0x7f080078
			public const int tooltipTitle = 2131230840;
			
			// aapt resource value: 0x7f0800fb
			public const int totalContent = 2131230971;
			
			// aapt resource value: 0x7f0800f5
			public const int totalContent111 = 2131230965;
			
			// aapt resource value: 0x7f080062
			public const int tvAltitude = 2131230818;
			
			// aapt resource value: 0x7f08005b
			public const int tvBpm = 2131230811;
			
			// aapt resource value: 0x7f080058
			public const int tvDistance = 2131230808;
			
			// aapt resource value: 0x7f080053
			public const int tvSpeed = 2131230803;
			
			// aapt resource value: 0x7f080060
			public const int tvWatt = 2131230816;
			
			// aapt resource value: 0x7f0800a3
			public const int txt10KRun = 2131230883;
			
			// aapt resource value: 0x7f080116
			public const int txtATL = 2131230998;
			
			// aapt resource value: 0x7f08016f
			public const int txtAge = 2131231087;
			
			// aapt resource value: 0x7f0800db
			public const int txtBFTPHB = 2131230939;
			
			// aapt resource value: 0x7f0800dc
			public const int txtBFTPower = 2131230940;
			
			// aapt resource value: 0x7f080090
			public const int txtBMI = 2131230864;
			
			// aapt resource value: 0x7f0800d1
			public const int txtBZone1HR = 2131230929;
			
			// aapt resource value: 0x7f0800d2
			public const int txtBZone1POWER = 2131230930;
			
			// aapt resource value: 0x7f0800d3
			public const int txtBZone2HR = 2131230931;
			
			// aapt resource value: 0x7f0800d4
			public const int txtBZone2POWER = 2131230932;
			
			// aapt resource value: 0x7f0800d5
			public const int txtBZone3HR = 2131230933;
			
			// aapt resource value: 0x7f0800d6
			public const int txtBZone3POWER = 2131230934;
			
			// aapt resource value: 0x7f0800d7
			public const int txtBZone4HR = 2131230935;
			
			// aapt resource value: 0x7f0800d8
			public const int txtBZone4POWER = 2131230936;
			
			// aapt resource value: 0x7f0800d9
			public const int txtBZone5HR = 2131230937;
			
			// aapt resource value: 0x7f0800da
			public const int txtBZone5POWER = 2131230938;
			
			// aapt resource value: 0x7f080119
			public const int txtCTL = 2131231001;
			
			// aapt resource value: 0x7f080031
			public const int txtComment = 2131230769;
			
			// aapt resource value: 0x7f08011f
			public const int txtDailyIF = 2131231007;
			
			// aapt resource value: 0x7f08011c
			public const int txtDailyTSS = 2131231004;
			
			// aapt resource value: 0x7f0800a2
			public const int txtDistance = 2131230882;
			
			// aapt resource value: 0x7f080144
			public const int txtEmail = 2131231044;
			
			// aapt resource value: 0x7f08016c
			public const int txtErrorUsername = 2131231084;
			
			// aapt resource value: 0x7f080091
			public const int txtFatPercentage = 2131230865;
			
			// aapt resource value: 0x7f080162
			public const int txtFirstname = 2131231074;
			
			// aapt resource value: 0x7f080097
			public const int txtGoalDate = 2131230871;
			
			// aapt resource value: 0x7f080099
			public const int txtGoalLoad = 2131230873;
			
			// aapt resource value: 0x7f080098
			public const int txtGoalName = 2131230872;
			
			// aapt resource value: 0x7f0800a1
			public const int txtHDistance = 2131230881;
			
			// aapt resource value: 0x7f0800a4
			public const int txtHMarathon = 2131230884;
			
			// aapt resource value: 0x7f08008f
			public const int txtHeight = 2131230863;
			
			// aapt resource value: 0x7f080165
			public const int txtLastname = 2131231077;
			
			// aapt resource value: 0x7f0800a5
			public const int txtMarathon = 2131230885;
			
			// aapt resource value: 0x7f0800a0
			public const int txtOlympic = 2131230880;
			
			// aapt resource value: 0x7f08006f
			public const int txtPassword = 2131230831;
			
			// aapt resource value: 0x7f080073
			public const int txtPwConfirm = 2131230835;
			
			// aapt resource value: 0x7f0800ce
			public const int txtRFTPHB = 2131230926;
			
			// aapt resource value: 0x7f0800cd
			public const int txtRFTPace = 2131230925;
			
			// aapt resource value: 0x7f0800cf
			public const int txtRFTPower = 2131230927;
			
			// aapt resource value: 0x7f0800be
			public const int txtRZone1HR = 2131230910;
			
			// aapt resource value: 0x7f0800bf
			public const int txtRZone1PACE = 2131230911;
			
			// aapt resource value: 0x7f0800c0
			public const int txtRZone1Power = 2131230912;
			
			// aapt resource value: 0x7f0800c1
			public const int txtRZone2HR = 2131230913;
			
			// aapt resource value: 0x7f0800c2
			public const int txtRZone2PACE = 2131230914;
			
			// aapt resource value: 0x7f0800c3
			public const int txtRZone2Power = 2131230915;
			
			// aapt resource value: 0x7f0800c4
			public const int txtRZone3HR = 2131230916;
			
			// aapt resource value: 0x7f0800c5
			public const int txtRZone3PACE = 2131230917;
			
			// aapt resource value: 0x7f0800c6
			public const int txtRZone3Power = 2131230918;
			
			// aapt resource value: 0x7f0800c7
			public const int txtRZone4HR = 2131230919;
			
			// aapt resource value: 0x7f0800c8
			public const int txtRZone4PACE = 2131230920;
			
			// aapt resource value: 0x7f0800c9
			public const int txtRZone4Power = 2131230921;
			
			// aapt resource value: 0x7f0800ca
			public const int txtRZone5HR = 2131230922;
			
			// aapt resource value: 0x7f0800cb
			public const int txtRZone5PACE = 2131230923;
			
			// aapt resource value: 0x7f0800cc
			public const int txtRZone5Power = 2131230924;
			
			// aapt resource value: 0x7f0800ad
			public const int txtRankBike = 2131230893;
			
			// aapt resource value: 0x7f0800ac
			public const int txtRankRun = 2131230892;
			
			// aapt resource value: 0x7f0800ab
			public const int txtRankSwim = 2131230891;
			
			// aapt resource value: 0x7f0800bc
			public const int txtSFTPHB = 2131230908;
			
			// aapt resource value: 0x7f0800bb
			public const int txtSFTPace = 2131230907;
			
			// aapt resource value: 0x7f0800b1
			public const int txtSZone1HR = 2131230897;
			
			// aapt resource value: 0x7f0800b2
			public const int txtSZone1PACE = 2131230898;
			
			// aapt resource value: 0x7f0800b3
			public const int txtSZone2HR = 2131230899;
			
			// aapt resource value: 0x7f0800b4
			public const int txtSZone2PACE = 2131230900;
			
			// aapt resource value: 0x7f0800b5
			public const int txtSZone3HR = 2131230901;
			
			// aapt resource value: 0x7f0800b6
			public const int txtSZone3PACE = 2131230902;
			
			// aapt resource value: 0x7f0800b7
			public const int txtSZone4HR = 2131230903;
			
			// aapt resource value: 0x7f0800b8
			public const int txtSZone4PACE = 2131230904;
			
			// aapt resource value: 0x7f0800b9
			public const int txtSZone5HR = 2131230905;
			
			// aapt resource value: 0x7f0800ba
			public const int txtSZone5PACE = 2131230906;
			
			// aapt resource value: 0x7f08009f
			public const int txtSprint = 2131230879;
			
			// aapt resource value: 0x7f080113
			public const int txtTSB = 2131230995;
			
			// aapt resource value: 0x7f080154
			public const int txtTime = 2131231060;
			
			// aapt resource value: 0x7f080153
			public const int txtTitle = 2131231059;
			
			// aapt resource value: 0x7f080169
			public const int txtUsername = 2131231081;
			
			// aapt resource value: 0x7f08008e
			public const int txtWeight = 2131230862;
			
			// aapt resource value: 0x7f080184
			public const int vertical2 = 2131231108;
			
			// aapt resource value: 0x7f08009e
			public const int viewBestResults = 2131230878;
			
			// aapt resource value: 0x7f0800f1
			public const int viewCycle = 2131230961;
			
			// aapt resource value: 0x7f080096
			public const int viewGoals = 2131230870;
			
			// aapt resource value: 0x7f0800e1
			public const int viewPager = 2131230945;
			
			// aapt resource value: 0x7f08008d
			public const int viewPhysical = 2131230861;
			
			// aapt resource value: 0x7f080109
			public const int viewRun = 2131230985;
			
			// aapt resource value: 0x7f0800a9
			public const int viewSelfRankings = 2131230889;
			
			// aapt resource value: 0x7f080133
			public const int viewSwim = 2131231027;
			
			// aapt resource value: 0x7f08013b
			public const int whatItLabel = 2131231035;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddCommentActivity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AdjustTrainningActivity = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AnalyticsActivity = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int annotation_tooltip = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ChangePasswordActivity = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int day_layout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int default_marker = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int EditProfileActivity = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int EventCalendarActivity = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int EventInstructionActivity = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int fCalendar = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int fEvents = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int ForgotPasswordActivity = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int fProfile = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int InitActivity = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int item_Comment = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int item_NitroEvent = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int item_PointInfoView = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int ItemViewPagerCalendar = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int loading = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int loadingimage = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int loadingprogress = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int LocationActivity = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int LoginActivity = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int RegisterActivity = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int SelectPTypeActivity = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int SwipeTabActivity = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int tooltip = 2130903067;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int ApplicationName = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int Hello = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int app_name = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int demo_max_label = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int demo_min_label = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppBaseTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int AppTheme = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int BlackEditBox = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int BlackEditBoxWithImage = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int EditBoxIcon = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int MyTheme_Splash = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AutofitTextView = new int[]
			{
					2130772102,
					2130772103,
					2130772104};
			
			// aapt resource value: 0
			public const int AutofitTextView_minTextSize = 0;
			
			// aapt resource value: 1
			public const int AutofitTextView_precision = 1;
			
			// aapt resource value: 2
			public const int AutofitTextView_sizeToFit = 2;
			
			public static int[] FlexChart = new int[]
			{
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014,
					2130772015,
					2130772016,
					2130772017,
					2130772018,
					2130772019,
					2130772020,
					2130772021,
					2130772022,
					2130772023,
					2130772024,
					2130772025,
					2130772026,
					2130772027,
					2130772028,
					2130772029,
					2130772030,
					2130772031,
					2130772032,
					2130772033,
					2130772034,
					2130772035,
					2130772036,
					2130772037,
					2130772038,
					2130772039,
					2130772040,
					2130772041,
					2130772042,
					2130772043,
					2130772044,
					2130772045,
					2130772046,
					2130772047,
					2130772048,
					2130772049,
					2130772050,
					2130772051,
					2130772052,
					2130772053,
					2130772054,
					2130772055,
					2130772056,
					2130772057,
					2130772058,
					2130772059,
					2130772060,
					2130772061,
					2130772062,
					2130772063,
					2130772064,
					2130772065,
					2130772066,
					2130772067,
					2130772068,
					2130772069,
					2130772070,
					2130772071,
					2130772072,
					2130772073,
					2130772074,
					2130772075,
					2130772076,
					2130772077,
					2130772078,
					2130772079,
					2130772080,
					2130772081,
					2130772082,
					2130772083,
					2130772084,
					2130772085,
					2130772086,
					2130772087,
					2130772088,
					2130772089,
					2130772090,
					2130772091,
					2130772092,
					2130772093,
					2130772094,
					2130772095,
					2130772096,
					2130772097,
					2130772098,
					2130772099,
					2130772100,
					2130772101};
			
			// aapt resource value: 51
			public const int FlexChart_flexChart_animated = 51;
			
			// aapt resource value: 11
			public const int FlexChart_flexChart_axisX_axisLineVisible = 11;
			
			// aapt resource value: 78
			public const int FlexChart_flexChart_axisX_format = 78;
			
			// aapt resource value: 62
			public const int FlexChart_flexChart_axisX_labelAngle = 62;
			
			// aapt resource value: 59
			public const int FlexChart_flexChart_axisX_labelFontColor = 59;
			
			// aapt resource value: 60
			public const int FlexChart_flexChart_axisX_labelFontSize = 60;
			
			// aapt resource value: 61
			public const int FlexChart_flexChart_axisX_labelFontTypeface = 61;
			
			// aapt resource value: 8
			public const int FlexChart_flexChart_axisX_labelFontWeight = 8;
			
			// aapt resource value: 10
			public const int FlexChart_flexChart_axisX_labelsVisible = 10;
			
			// aapt resource value: 66
			public const int FlexChart_flexChart_axisX_lineColor = 66;
			
			// aapt resource value: 67
			public const int FlexChart_flexChart_axisX_lineWidth = 67;
			
			// aapt resource value: 84
			public const int FlexChart_flexChart_axisX_logBase = 84;
			
			// aapt resource value: 68
			public const int FlexChart_flexChart_axisX_majorGridColor = 68;
			
			// aapt resource value: 72
			public const int FlexChart_flexChart_axisX_majorGridFill = 72;
			
			// aapt resource value: 13
			public const int FlexChart_flexChart_axisX_majorGridVisible = 13;
			
			// aapt resource value: 69
			public const int FlexChart_flexChart_axisX_majorGridWidth = 69;
			
			// aapt resource value: 70
			public const int FlexChart_flexChart_axisX_majorTickColor = 70;
			
			// aapt resource value: 12
			public const int FlexChart_flexChart_axisX_majorTickOverlap = 12;
			
			// aapt resource value: 71
			public const int FlexChart_flexChart_axisX_majorTickWidth = 71;
			
			// aapt resource value: 80
			public const int FlexChart_flexChart_axisX_majorUnit = 80;
			
			// aapt resource value: 73
			public const int FlexChart_flexChart_axisX_minorGridColor = 73;
			
			// aapt resource value: 77
			public const int FlexChart_flexChart_axisX_minorGridFill = 77;
			
			// aapt resource value: 15
			public const int FlexChart_flexChart_axisX_minorGridVisible = 15;
			
			// aapt resource value: 74
			public const int FlexChart_flexChart_axisX_minorGridWidth = 74;
			
			// aapt resource value: 75
			public const int FlexChart_flexChart_axisX_minorTickColor = 75;
			
			// aapt resource value: 14
			public const int FlexChart_flexChart_axisX_minorTickOverlap = 14;
			
			// aapt resource value: 76
			public const int FlexChart_flexChart_axisX_minorTickWidth = 76;
			
			// aapt resource value: 81
			public const int FlexChart_flexChart_axisX_minorUnit = 81;
			
			// aapt resource value: 83
			public const int FlexChart_flexChart_axisX_name = 83;
			
			// aapt resource value: 79
			public const int FlexChart_flexChart_axisX_origin = 79;
			
			// aapt resource value: 85
			public const int FlexChart_flexChart_axisX_overlappingLabels = 85;
			
			// aapt resource value: 82
			public const int FlexChart_flexChart_axisX_title = 82;
			
			// aapt resource value: 63
			public const int FlexChart_flexChart_axisX_titleFontColor = 63;
			
			// aapt resource value: 64
			public const int FlexChart_flexChart_axisX_titleFontSize = 64;
			
			// aapt resource value: 65
			public const int FlexChart_flexChart_axisX_titleFontTypeface = 65;
			
			// aapt resource value: 9
			public const int FlexChart_flexChart_axisX_titleFontWeight = 9;
			
			// aapt resource value: 19
			public const int FlexChart_flexChart_axisY_axisLineVisible = 19;
			
			// aapt resource value: 86
			public const int FlexChart_flexChart_axisY_format = 86;
			
			// aapt resource value: 90
			public const int FlexChart_flexChart_axisY_labelAngle = 90;
			
			// aapt resource value: 87
			public const int FlexChart_flexChart_axisY_labelFontColor = 87;
			
			// aapt resource value: 88
			public const int FlexChart_flexChart_axisY_labelFontSize = 88;
			
			// aapt resource value: 89
			public const int FlexChart_flexChart_axisY_labelFontTypeface = 89;
			
			// aapt resource value: 16
			public const int FlexChart_flexChart_axisY_labelFontWeight = 16;
			
			// aapt resource value: 18
			public const int FlexChart_flexChart_axisY_labelsVisible = 18;
			
			// aapt resource value: 94
			public const int FlexChart_flexChart_axisY_lineColor = 94;
			
			// aapt resource value: 95
			public const int FlexChart_flexChart_axisY_lineWidth = 95;
			
			// aapt resource value: 111
			public const int FlexChart_flexChart_axisY_logBase = 111;
			
			// aapt resource value: 96
			public const int FlexChart_flexChart_axisY_majorGridColor = 96;
			
			// aapt resource value: 100
			public const int FlexChart_flexChart_axisY_majorGridFill = 100;
			
			// aapt resource value: 20
			public const int FlexChart_flexChart_axisY_majorGridVisible = 20;
			
			// aapt resource value: 97
			public const int FlexChart_flexChart_axisY_majorGridWidth = 97;
			
			// aapt resource value: 98
			public const int FlexChart_flexChart_axisY_majorTickColor = 98;
			
			// aapt resource value: 21
			public const int FlexChart_flexChart_axisY_majorTickOverlap = 21;
			
			// aapt resource value: 99
			public const int FlexChart_flexChart_axisY_majorTickWidth = 99;
			
			// aapt resource value: 107
			public const int FlexChart_flexChart_axisY_majorUnit = 107;
			
			// aapt resource value: 101
			public const int FlexChart_flexChart_axisY_minorGridColor = 101;
			
			// aapt resource value: 105
			public const int FlexChart_flexChart_axisY_minorGridFill = 105;
			
			// aapt resource value: 22
			public const int FlexChart_flexChart_axisY_minorGridVisible = 22;
			
			// aapt resource value: 102
			public const int FlexChart_flexChart_axisY_minorGridWidth = 102;
			
			// aapt resource value: 103
			public const int FlexChart_flexChart_axisY_minorTickColor = 103;
			
			// aapt resource value: 23
			public const int FlexChart_flexChart_axisY_minorTickOverlap = 23;
			
			// aapt resource value: 104
			public const int FlexChart_flexChart_axisY_minorTickWidth = 104;
			
			// aapt resource value: 108
			public const int FlexChart_flexChart_axisY_minorUnit = 108;
			
			// aapt resource value: 110
			public const int FlexChart_flexChart_axisY_name = 110;
			
			// aapt resource value: 106
			public const int FlexChart_flexChart_axisY_origin = 106;
			
			// aapt resource value: 112
			public const int FlexChart_flexChart_axisY_overlappingLabels = 112;
			
			// aapt resource value: 109
			public const int FlexChart_flexChart_axisY_title = 109;
			
			// aapt resource value: 91
			public const int FlexChart_flexChart_axisY_titleFontColor = 91;
			
			// aapt resource value: 92
			public const int FlexChart_flexChart_axisY_titleFontSize = 92;
			
			// aapt resource value: 93
			public const int FlexChart_flexChart_axisY_titleFontTypeface = 93;
			
			// aapt resource value: 17
			public const int FlexChart_flexChart_axisY_titleFontWeight = 17;
			
			// aapt resource value: 33
			public const int FlexChart_flexChart_backgroundColor = 33;
			
			// aapt resource value: 50
			public const int FlexChart_flexChart_binding = 50;
			
			// aapt resource value: 34
			public const int FlexChart_flexChart_borderColor = 34;
			
			// aapt resource value: 35
			public const int FlexChart_flexChart_borderWidth = 35;
			
			// aapt resource value: 48
			public const int FlexChart_flexChart_chartOptions_bubbleMaxSize = 48;
			
			// aapt resource value: 47
			public const int FlexChart_flexChart_chartOptions_bubbleMinSize = 47;
			
			// aapt resource value: 49
			public const int FlexChart_flexChart_chartOptions_groupWidth = 49;
			
			// aapt resource value: 6
			public const int FlexChart_flexChart_chartType = 6;
			
			// aapt resource value: 116
			public const int FlexChart_flexChart_datalabel_FontColor = 116;
			
			// aapt resource value: 118
			public const int FlexChart_flexChart_datalabel_FontSize = 118;
			
			// aapt resource value: 119
			public const int FlexChart_flexChart_datalabel_FontTypeface = 119;
			
			// aapt resource value: 5
			public const int FlexChart_flexChart_datalabel_FontWeight = 5;
			
			// aapt resource value: 114
			public const int FlexChart_flexChart_datalabel_backgroundColor = 114;
			
			// aapt resource value: 115
			public const int FlexChart_flexChart_datalabel_borderColor = 115;
			
			// aapt resource value: 117
			public const int FlexChart_flexChart_datalabel_borderWidth = 117;
			
			// aapt resource value: 113
			public const int FlexChart_flexChart_datalabel_position = 113;
			
			// aapt resource value: 29
			public const int FlexChart_flexChart_footer = 29;
			
			// aapt resource value: 32
			public const int FlexChart_flexChart_footerFontColor = 32;
			
			// aapt resource value: 3
			public const int FlexChart_flexChart_footerFontGravity = 3;
			
			// aapt resource value: 30
			public const int FlexChart_flexChart_footerFontSize = 30;
			
			// aapt resource value: 31
			public const int FlexChart_flexChart_footerFontTypeface = 31;
			
			// aapt resource value: 2
			public const int FlexChart_flexChart_footerFontWeight = 2;
			
			// aapt resource value: 25
			public const int FlexChart_flexChart_header = 25;
			
			// aapt resource value: 28
			public const int FlexChart_flexChart_headerFontColor = 28;
			
			// aapt resource value: 1
			public const int FlexChart_flexChart_headerFontGravity = 1;
			
			// aapt resource value: 26
			public const int FlexChart_flexChart_headerFontSize = 26;
			
			// aapt resource value: 27
			public const int FlexChart_flexChart_headerFontTypeface = 27;
			
			// aapt resource value: 0
			public const int FlexChart_flexChart_headerFontWeight = 0;
			
			// aapt resource value: 42
			public const int FlexChart_flexChart_legend_FontColor = 42;
			
			// aapt resource value: 43
			public const int FlexChart_flexChart_legend_FontSize = 43;
			
			// aapt resource value: 44
			public const int FlexChart_flexChart_legend_FontTypeface = 44;
			
			// aapt resource value: 4
			public const int FlexChart_flexChart_legend_FontWeight = 4;
			
			// aapt resource value: 39
			public const int FlexChart_flexChart_legend_backgroundColor = 39;
			
			// aapt resource value: 40
			public const int FlexChart_flexChart_legend_borderColor = 40;
			
			// aapt resource value: 41
			public const int FlexChart_flexChart_legend_borderWidth = 41;
			
			// aapt resource value: 45
			public const int FlexChart_flexChart_legend_orientation = 45;
			
			// aapt resource value: 46
			public const int FlexChart_flexChart_legend_position = 46;
			
			// aapt resource value: 55
			public const int FlexChart_flexChart_loadAnimation_duration = 55;
			
			// aapt resource value: 54
			public const int FlexChart_flexChart_loadAnimation_loadAnimationMode = 54;
			
			// aapt resource value: 56
			public const int FlexChart_flexChart_loadAnimation_startDelay = 56;
			
			// aapt resource value: 24
			public const int FlexChart_flexChart_palette = 24;
			
			// aapt resource value: 36
			public const int FlexChart_flexChart_plotAreabackgroundColor = 36;
			
			// aapt resource value: 37
			public const int FlexChart_flexChart_selectedBorderColor = 37;
			
			// aapt resource value: 38
			public const int FlexChart_flexChart_selectedBorderWidth = 38;
			
			// aapt resource value: 7
			public const int FlexChart_flexChart_stackingType = 7;
			
			// aapt resource value: 53
			public const int FlexChart_flexChart_toggleLegend = 53;
			
			// aapt resource value: 57
			public const int FlexChart_flexChart_updateAnimation_duration = 57;
			
			// aapt resource value: 58
			public const int FlexChart_flexChart_updateAnimation_startDelay = 58;
			
			// aapt resource value: 52
			public const int FlexChart_flexChart_zoomMode = 52;
			
			public static int[] ProgressWheel = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			public static int[] RangeSliderControl = new int[]
			{
					2130772105,
					2130772106,
					2130772107,
					2130772108,
					2130772109,
					2130772110,
					2130772111,
					2130772112,
					2130772113,
					2130772114,
					2130772115,
					2130772116,
					2130772117,
					2130772118,
					2130772119,
					2130772120,
					2130772121,
					2130772122,
					2130772123,
					2130772124,
					2130772125,
					2130772126,
					2130772127,
					2130772128};
			
			// aapt resource value: 1
			public const int RangeSliderControl_absoluteMaxValue = 1;
			
			// aapt resource value: 0
			public const int RangeSliderControl_absoluteMinValue = 0;
			
			// aapt resource value: 20
			public const int RangeSliderControl_activateOnDefaultValues = 20;
			
			// aapt resource value: 10
			public const int RangeSliderControl_activeColor = 10;
			
			// aapt resource value: 5
			public const int RangeSliderControl_alwaysActive = 5;
			
			// aapt resource value: 8
			public const int RangeSliderControl_barHeight = 8;
			
			// aapt resource value: 9
			public const int RangeSliderControl_defaultColor = 9;
			
			// aapt resource value: 7
			public const int RangeSliderControl_internalPadding = 7;
			
			// aapt resource value: 3
			public const int RangeSliderControl_maxThumbHidden = 3;
			
			// aapt resource value: 2
			public const int RangeSliderControl_minThumbHidden = 2;
			
			// aapt resource value: 4
			public const int RangeSliderControl_showRangeLabels = 4;
			
			// aapt resource value: 21
			public const int RangeSliderControl_stepValue = 21;
			
			// aapt resource value: 22
			public const int RangeSliderControl_stepValueContinuously = 22;
			
			// aapt resource value: 11
			public const int RangeSliderControl_textAboveThumbsColor = 11;
			
			// aapt resource value: 23
			public const int RangeSliderControl_textSize = 23;
			
			// aapt resource value: 14
			public const int RangeSliderControl_thumbDisabled = 14;
			
			// aapt resource value: 12
			public const int RangeSliderControl_thumbNormal = 12;
			
			// aapt resource value: 13
			public const int RangeSliderControl_thumbPressed = 13;
			
			// aapt resource value: 15
			public const int RangeSliderControl_thumbShadow = 15;
			
			// aapt resource value: 19
			public const int RangeSliderControl_thumbShadowBlur = 19;
			
			// aapt resource value: 16
			public const int RangeSliderControl_thumbShadowColor = 16;
			
			// aapt resource value: 17
			public const int RangeSliderControl_thumbShadowXOffset = 17;
			
			// aapt resource value: 18
			public const int RangeSliderControl_thumbShadowYOffset = 18;
			
			// aapt resource value: 6
			public const int RangeSliderControl_valuesAboveThumbs = 6;
			
			public static int[] XuniCalendar;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
